import Link from "next/link";
import { notFound } from "next/navigation";
import { asc, eq } from "drizzle-orm";
import { db } from "@/db";
import { invoiceLineItems, invoices, payments } from "@/db/schema";
import { INVOICE_STATUS_META, type InvoiceStatus } from "@/lib/billing";
import { isUuid } from "@/lib/forms";
import { formatCents } from "@/lib/money";
import { requireRole } from "@/lib/session";
import { PrintButton } from "./print-button";

// Lives outside /dashboard so it renders without the app chrome — a clean,
// printable document. requireRole still gates it server-side.
export default async function InvoicePrintPage({
  params,
}: {
  params: Promise<{ id: string }>;
}) {
  const { user } = await requireRole("tutor");
  const { id } = await params;
  if (!isUuid(id)) notFound();

  const invoice = await db.query.invoices.findFirst({
    where: eq(invoices.id, id),
    with: {
      client: true,
      lineItems: { orderBy: [asc(invoiceLineItems.description)] },
      payments: { orderBy: [asc(payments.paidAt)] },
    },
  });
  if (!invoice) notFound();

  const status = invoice.status as InvoiceStatus;
  const meta = INVOICE_STATUS_META[status];
  const total = invoice.lineItems.reduce((sum, li) => sum + li.amountCents, 0);
  const paid = invoice.payments.reduce((sum, p) => sum + p.amountCents, 0);
  const balance = Math.max(total - paid, 0);

  return (
    <div className="min-h-screen bg-base-200 print:bg-white p-6 print:p-0">
      <div className="max-w-2xl mx-auto flex items-center justify-between mb-4 print:hidden">
        <Link href={`/dashboard/invoices/${invoice.id}`} className="btn btn-ghost btn-sm">
          ← Back
        </Link>
        <PrintButton />
      </div>

      <div className="max-w-2xl mx-auto bg-white text-black shadow-sm print:shadow-none p-10">
        <div className="flex items-start justify-between">
          <div>
            <h1 className="text-3xl font-bold">Invoice</h1>
            <div className="text-gray-500">#{invoice.number}</div>
          </div>
          <span className={`badge ${meta.badge}`}>{meta.label}</span>
        </div>

        <div className="grid grid-cols-2 gap-6 mt-8 text-sm">
          <div>
            <div className="text-gray-500 uppercase text-xs tracking-wide">From</div>
            <div className="font-medium">{user.name}</div>
          </div>
          <div>
            <div className="text-gray-500 uppercase text-xs tracking-wide">
              Bill to
            </div>
            <div className="font-medium">{invoice.client.name}</div>
            {invoice.client.email && <div>{invoice.client.email}</div>}
            {invoice.client.phone && <div>{invoice.client.phone}</div>}
          </div>
          <div>
            <div className="text-gray-500 uppercase text-xs tracking-wide">
              Issued
            </div>
            <div>{invoice.issuedOn ?? "—"}</div>
          </div>
          <div>
            <div className="text-gray-500 uppercase text-xs tracking-wide">Due</div>
            <div>{invoice.dueOn ?? "—"}</div>
          </div>
        </div>

        <table className="w-full mt-8 text-sm">
          <thead>
            <tr className="border-b border-gray-300 text-left">
              <th className="py-2">Description</th>
              <th className="py-2 text-right">Amount</th>
            </tr>
          </thead>
          <tbody>
            {invoice.lineItems.map((li) => (
              <tr key={li.id} className="border-b border-gray-100">
                <td className="py-2">{li.description}</td>
                <td className="py-2 text-right whitespace-nowrap">
                  {formatCents(li.amountCents)}
                </td>
              </tr>
            ))}
          </tbody>
          <tfoot>
            <tr className="border-t border-gray-300">
              <th className="py-2 text-left">Total</th>
              <th className="py-2 text-right">{formatCents(total)}</th>
            </tr>
            {paid > 0 && (
              <>
                <tr>
                  <td className="py-1 text-left text-gray-500">Paid</td>
                  <td className="py-1 text-right text-gray-500">
                    −{formatCents(paid)}
                  </td>
                </tr>
                <tr>
                  <th className="py-1 text-left">Balance due</th>
                  <th className="py-1 text-right">{formatCents(balance)}</th>
                </tr>
              </>
            )}
          </tfoot>
        </table>

        <p className="text-xs text-gray-400 mt-10">
          Generated by TutorStar · Invoice #{invoice.number}
        </p>
      </div>
    </div>
  );
}
